`default_nettype none
/*
 * Emulation test on the ULX3S FPGA Board
 *
 * Plug the Digilent PmodSSD into the right side, top row.
 * Plug the Joystick into the left side, top row, upper half (GPIO GN[0-3])
 */
module EmulationTest_Joystick (
    input  logic clock,
    input  logic reset_n,
    output logic blinking_led
);

    logic [31:0] ctr;

    always_ff @(posedge clock) begin
        if (~reset_n) begin
            blinking_led <= '0;
            ctr <= '0;
        end
        else begin
            ctr <= ctr + 1;
            if (ctr == 32'd12_500_000) begin // 12.5M = 1/2 second
                ctr <= '0;
                blinking_led <= ~blinking_led;
            end
        end
    end

endmodule : EmulationTest_Joystick

module hex_to_sseg
  (input  logic [3:0] hex,
   input  logic       blank, all,
   output logic [6:0] sseg);

   logic [6:0] _sseg; // internal version

   always_comb
     if (blank)
       sseg = '0;
     else if (all)
       sseg = '1;
     else
       sseg = _sseg;

  always_comb begin
    _sseg = '0;
    case (hex)
      4'h0 : _sseg = 7'b1111_110; // A segment is MSB, active high
      4'h1 : _sseg = 7'b0110_000;
      4'h2 : _sseg = 7'b1101_101;
      4'h3 : _sseg = 7'b1111_001;
      4'h4 : _sseg = 7'b0110_011;
      4'h5 : _sseg = 7'b1011_011;
      4'h6 : _sseg = 7'b1011_111;
      4'h7 : _sseg = 7'b1110_000;
      4'h8 : _sseg = 7'b1111_111;
      4'h9 : _sseg = 7'b1111_011;
      4'hA : _sseg = 7'b1110_111;
      4'hB : _sseg = 7'b0011_111;
      4'hc : _sseg = 7'b0001_101;
      4'hd : _sseg = 7'b0111_101;
      4'he : _sseg = 7'b1001_111;
      4'hf : _sseg = 7'b1000_111;
      default : _sseg = 7'b1001_010; // 3 bars is error
    endcase
  end

endmodule : hex_to_sseg

// A driver of the cathode refresh signal
module PMOD_SSeg
  (input  logic [ 6: 0] sseg_left, sseg_right, // MSB is Segment A, active high segments
   input  logic         reset_n, clock,
   output logic [24:14] gn_values);

   parameter MSB = 18;

   logic [MSB:0] count;
   always_ff @(posedge clock, negedge reset_n)
     if (~reset_n)
       count <= '0;
     else
       count <= count + 1;

  assign gn_values[14] = count[MSB]; // display selection changes at least every 20msec

  always_comb
    if (count[MSB] === 1'b1)
      gn_values[24:15] = {sseg_left[6:3], 3'b0, sseg_left[2:0]};
    else
      gn_values[24:15] = {sseg_right[6:3], 3'b0, sseg_right[2:0]};

endmodule : PMOD_SSeg

module chipInterface (
    input logic clk_25mhz, // 25MHz clock
    //input logic reset_n, // Active-low reset

    input  logic [3:0] sw,  // DIP Switches
    output logic [7:0] led, // LEDs
    input  logic [6:0] btn, // btn[0] is BTN_PWRn (inverted logic)
                            // btn[1] is FIRE1
                            // btn[2] is FIRE2
                            // btn[3] is UP W1->R18
                            // btn[4] is DOWN
                            // btn[5] is LEFT
                            // btn[6] is RIGHT Y2->H16
    output logic [27:0] gn, // GPIO.  Top row of the connector
    );

    logic pll_locked, clock, blinking_led, reset_n, reset;

    assign reset_n = btn[0];
    assign reset = ~reset_n;

    assign led = {pll_locked, btn[6:1], blinking_led};

    logic [7:0] hexes;
    logic [6:0] sseg_left, sseg_right;


    hex_to_sseg hs0(.hex(hexes[7:4]),
                    .blank(1'b0),
                    .all(1'b0),
                    .sseg(sseg_left));

    hex_to_sseg hs1(.hex(hexes[3:0]),
                    .blank(1'b0),
                    .all(1'b0),
                    .sseg(sseg_right));

    PMOD_SSeg pss(.clock,
                  .reset_n,
                  .gn_values(gn[24:14]),
                  .sseg_left,
                  .sseg_right);

    logic mosi, miso, slave_select_n, sclk;
    assign gn[0] = sclk;
    assign gn[1] = miso;
    assign gn[2] = mosi;
    assign gn[3] = slave_select_n;

    SPI_Joystick sj(.clock(clk_25mhz),
                    .reset,
                    .mosi
                    .slave_select_n,
                    .sclk,
                    .miso,
                    .joy_x,
                    .joy_y,
                    .btn_j,
                    .btn_t,
                    .new_values,
                    .ledr,
                    .ledg,
                    .ledb
                   );

    // Connects to PLL generated by
    // ecppll -i 25 -o 32 --highres -f blinky_pll.sv -n clock_divider
    //        --clkin_name clk_25mhz --clkout0_name clock_32mhz
    clock_divider cd(.clk_25mhz, // 25 MHz, 0 deg
                     .clock_32mhz(clock), // 32 MHz, 0 deg
                     .locked(pll_locked)
    );

endmodule

